import {Providers} from "./providers";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import type { Metadata } from 'next'
import './globals.css';

export const metadata: Metadata = {
  title: 'Tracktive',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Providers>
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  )
}
